module.exports = {
	'server':'https://horizon-testnet.stellar.org',
	'account':'GDD7CBRNZBK66SPRXX6YHB6N3NLOI7Y3AXWXMMGTVBTUCK2TQX3J6FZP',
	'secret':'SAKKA7FQLPKSSLECP5SDJDRUQSWDF7PVYHNQG6JJBDFIFWQ5XM5SMIKS'
}