module.exports = {
	'server':'https://horizon-testnet.stellar.org',
	'account':'GABX5IOSCZLKXRC67LJHJCEXQQER5INJMYDEPI4ZXBHW52FPA6PB5FSY',
	'secret':'SDJWPRZXTAWVZA4ACIRKRT7KU7LKSZJUPMXPLL6SCQ4VMTEICYIUSSRQ'
}